# Generated by Django 5.2.12 on 2026-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('opening_hours', models.CharField(help_text='e.g. Mon-Fri: 9AM - 10PM', max_length=150)),
                ('gmap_link', models.URLField(help_text='Google Maps URL', max_length=500)),
                ('categories', models.ManyToManyField(related_name='restaurants', to='core.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
