# Generated by Django 5.2.12 on 2026-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='area',
            field=models.CharField(blank=True, help_text='e.g. South Jakarta', max_length=100, null=True),
        ),
    ]
