# Generated by Django 5.2.12 on 2026-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('map', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'resto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'resto_tag',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
